<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <LangVersion>latest</LangVersion>
        <CelestePath>..\..\..</CelestePath>
        <TargetFramework>net8</TargetFramework>
        <OutputPath>bin</OutputPath>
        <PackageId>ProgHelper</PackageId>
        <RootNamespace>ProgHelper</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="CelesteMod.Publicizer" Version="*" CelesteAssembly="$(CelestePath)\Celeste.dll" />
        <Reference Include="FNA">
            <HintPath>$(CelestePath)\FNA.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="GravityHelper">
          <HintPath>libs\GravityHelper.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="MMHOOK_Celeste">
            <HintPath>$(CelestePath)\MMHOOK_Celeste.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="VivHelper">
            <HintPath>libs\VivHelper.dll</HintPath>
            <Private>false</Private>
        </Reference>
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="MonoMod.RuntimeDetour" Version="25.3.3" />
    </ItemGroup>
</Project>
